# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintech-app
  template:
    metadata:
      labels:
        app: fintech-app
    spec:
      containers:
      - name: fintech-app
        image: tobaalo/fintech-project-pipeline:latest
        ports:
        - containerPort: 80
