# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fintech-app
spec:
  selector:
    app: fintech-app
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 3000  # matches containerPort in deployment
  type: LoadBalancer
